server:
  port: 8090


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/transaction-demo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: Xr20200101!
    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource2:
    url: jdbc:mysql://127.0.0.1:3306/transaction-demo1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
      password: Xr20200101!
    driver-class-name: com.mysql.cj.jdbc.Driver